alter sequence province_id_seq restart with 1;
INSERT INTO "province" ("name") VALUES
('Capital Federal'),
('Buenos Aires'),
('Catamarca'),
('Chaco'),
('Chubut'),
('Córdoba'),
('Corrientes'),
('Entre Ríos'),
('Formosa'),
('Jujuy'),
('La Pampa'),
('La Rioja'),
('Mendoza'),
('Misiones'),
('Neuquén'),
('Río Negro'),
('Salta'),
('San Juan'),
('San Luis'),
('Santa Cruz'),
('Santa Fe'),
('Santiago del Estero'),
('Tierra del Fuego'),
('Tucumán');

-- insert locations
alter sequence location_id_seq restart with 1;
INSERT INTO "location" ("name","province_id") VALUES
('Capital',1),
('CABA',2),
('La Plata',2),
('Córdoba',6),
('Herrera',8),
('Basavilbaso',8),
('Concepción del Uruguay',8),
('Colón',8),
('San José',8),
('Gualeguaychú',8),
('Concordia',8),
('Paraná',8),
('Villaguay',8),
('Gualeguay',8),
('Rosario del Tala',8),
('Chajarí',8),
('Nogoyá',8),
('Rosario',21),
('Santa Fé',21);